# 端口号
server:
  port: 8083

spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: UTF-8
    # 授权码(开通邮件SMTP服务时会有)
    password: xxxxxxxxxxxxxx
    # 发送者邮箱地址
    username: xxxxxxx@163.com
    # 端口(不同邮箱端口不同)
    port: 25
  # rabbitmq消息队列配置
  rabbitmq:
    # 用户名
    username: sunwul
    # 密码
    password: 123
    # 服务器地址
    host: localhost
    # 端口
    port: 5672
    #连接到的虚拟主机
    virtual-host: testhost
    # 设置监听为手动应答模式
    listener:
      simple:
         acknowledge-mode: manual
  # redis配置
  redis:
    # 服务地址
    host: localhost
    # 服务端口
    port: 6379
    # 超时时间
    timeout: 10000ms
    # 数据库
    database: 0
    # redis服务器连接密码(默认为空)
    password: sunwul
    #redis连接池配置 2.0中可以使用jedis或者lettuce配置连接池
    lettuce:
      pool:
        #最大连接数(默认为8,使用负值表示没有限制)
        max-active: 1024
        #最大连接阻塞等待时间(默认为-1,使用负值表示没有限制)
        max-wait: 10000ms
        #最大空闲连接(默认为8)
        max-idle: 200
        #最小空闲连接(默认为0)
        min-idle: 5
